name: Run Tests on push
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install ependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==1.13.1+cpu torchvision==0.14.1+cpu --extra-index-url https://download.pytorch.org/whl/cpu
          pip install tqdm==4.66.1
          pip install tifffile==2023.9.26
          pip install .

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          # When using pytest and pytorch at the same time, an error of multiple copied of OpenMP runtime library will rise.
          # This is a well known issue and is the reason of why pytorch uses unitest for testing and not pytest.
          # This is a non-recomended, non-supported, and therefore non-elegant solution for that problem, but at least let run the test suite.
          export KMP_DUPLICATE_LIB_OK=TRUE
          pytest tests --cov=zarrdataset
